# Generated by Django 5.1.1 on 2025-05-27 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_service_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.CharField(default='4 weeks', help_text='e.g. 4 weeks, 30 mins/session', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trainer'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('ri-bar-chart-line', 'Strength Training'), ('ri-body-scan-line', 'Body Scan'), ('ri-mind-map', 'Meditation'), ('ri-boxing-line', 'Boxing'), ('ri-heart-pulse-line', 'Cardio'), ('ri-fire-line', 'Fat Burn'), ('ri-timer-line', 'Timer'), ('ri-run-line', 'Running'), ('ri-user-star-line', 'Muscle Building'), ('ri-flashlight-line', 'Energy Boost'), ('ri-sparkling-line', 'Yoga Pose'), ('ri-bear-smile-line', 'Strength Smile'), ('ri-user-line', 'Personal Trainer'), ('ri-calendar-line', 'Schedule'), ('ri-water-flash-line', 'Hydration'), ('ri-arrow-left-right-line', 'Stretching'), ('ri-equalizer-line', 'Weight Control'), ('ri-check-double-line', 'Checklist Routine'), ('ri-hotel-bed-line', 'Recovery & Rest'), ('ri-blaze-line', 'Cardio Machine'), ('ri-group-line', 'Group Training'), ('ri-flag-line', 'Goal Setting'), ('ri-bar-chart-line', 'Progress Tracking'), ('ri-restaurant-line', 'Nutrition Advice'), ('ri-chat-smile-line', 'Coaching Support')], max_length=50),
        ),
    ]
