# Generated by Django 5.1.1 on 2025-05-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_description_service_long_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_image',
            field=models.ImageField(default='ICON', help_text='Upload SVG icon for this service', upload_to='icons/'),
            preserve_default=False,
        ),
    ]
