# Generated by Django 5.1.1 on 2025-05-28 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_service_icon_service_icon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='icons/')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon_image',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.icon'),
        ),
    ]
