# Generated by Django 5.1.1 on 2025-05-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_icon_remove_service_icon_image_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.FileField(help_text='Upload .svg, .png, or .jpg icon', upload_to='icons/'),
        ),
    ]
