# Generated by Django 5.1.1 on 2025-05-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_icon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_default',
            field=models.ImageField(default='Icon', help_text='Red or dark icon', upload_to='services/icons/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='icon_hover',
            field=models.ImageField(default='icon-white', help_text='White icon for hover effect', upload_to='services/icons/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/images/'),
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
