# Generated by Django 5.1.1 on 2025-05-28 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_service_icon_service_icon_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_icon', models.ImageField(help_text='Red or dark icon', upload_to='icons/default/')),
                ('hover_icon', models.ImageField(help_text='White icon for hover effect', upload_to='icons/hover/')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon_default',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon_hover',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.icon'),
        ),
    ]
