# Generated by Django 5.1.1 on 2025-05-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_icon_remove_service_icon_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='default_icon',
            field=models.FileField(help_text='Red or dark icon (SVG, PNG, JPG)', upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='hover_icon',
            field=models.FileField(help_text='White icon for hover effect (SVG, PNG, JPG)', upload_to='icons/'),
        ),
    ]
