# Generated by Django 5.1.1 on 2025-05-31 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_icon_default_icon_alter_icon_hover_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trainer'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='default_icon',
            field=models.FileField(help_text='Dark/default icon (SVG, PNG, JPG)', upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='hover_icon',
            field=models.FileField(help_text='Hover/light icon (SVG, PNG, JPG)', upload_to='icons/'),
        ),
    ]
