# Generated by Django 5.1.1 on 2025-05-31 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_classschedule_trainer_alter_icon_default_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service'),
        ),
    ]
