# Generated by Django 5.1.1 on 2025-05-31 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_classschedule_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='schedule_backgrounds/')),
            ],
        ),
        migrations.AddField(
            model_name='classschedule',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.schedulebackground'),
        ),
    ]
