# Generated by Django 5.1.1 on 2025-05-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_testimonial_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='E.g. STANDARD PLAN', max_length=100)),
                ('price', models.PositiveIntegerField(help_text='Plan price in INR')),
                ('duration_text', models.CharField(help_text='E.g. /Month, /3 Months', max_length=50)),
                ('image', models.ImageField(help_text='Plan image', upload_to='membership/')),
                ('features', models.TextField(blank=True, help_text='Add one feature per line')),
            ],
        ),
    ]
