# Generated by Django 5.1.1 on 2025-06-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_image_blog_main_image_remove_blog_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='This image appears in the blog hero/banner section', null=True, upload_to='blogs/banner/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(help_text='Main image used within blog content', upload_to='blogs/'),
        ),
    ]
