# Generated by Django 5.1.1 on 2025-06-01 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_blog_content_blog_views_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classschedule',
            old_name='name',
            new_name='class_name',
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='schedule_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.trainer'),
            preserve_default=False,
        ),
    ]
