# Generated by Django 5.1.1 on 2025-06-01 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_name_classschedule_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.schedulebackground'),
        ),
    ]
